/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppContext */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppContext
#define _Included_org_argeo_jjml_llama_LlamaCppContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doInit
 * Signature: (Lorg/argeo/jjml/llama/LlamaCppModel;Lorg/argeo/jjml/llama/LlamaCppContextParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doInit
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doDestroy
  (JNIEnv *, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doGetPoolingType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doGetPoolingType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
