/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppVocabulary */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppVocabulary
#define _Included_org_argeo_jjml_llama_LlamaCppVocabulary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8BytesAsArray
 * Signature: (J[BIIZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8BytesAsArray
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8AsArray
 * Signature: (JLjava/nio/ByteBuffer;ZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8AsArray
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8Bytes
 * Signature: (J[BIILjava/nio/IntBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8Bytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/IntBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeArrayAsUtf8Bytes
 * Signature: (J[IIIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeArrayAsUtf8Bytes
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsUtf8Bytes
 * Signature: (JLjava/nio/IntBuffer;ZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsUtf8Bytes
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeArrayAsUtf8
 * Signature: (J[IIILjava/nio/ByteBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeArrayAsUtf8
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsUtf8
 * Signature: (JLjava/nio/IntBuffer;Ljava/nio/ByteBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsUtf8
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeStringAsArray
 * Signature: (JLjava/lang/String;ZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeStringAsArray
  (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeString
 * Signature: (JLjava/lang/String;Ljava/nio/IntBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeString
  (JNIEnv *, jobject, jlong, jstring, jobject, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeArrayAsString
 * Signature: (J[IIIZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeArrayAsString
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsString
 * Signature: (JLjava/nio/IntBuffer;ZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsString
  (JNIEnv *, jobject, jlong, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
