/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppModel */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppModel
#define _Included_org_argeo_jjml_llama_LlamaCppModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doTokenize
 * Signature: (Ljava/lang/String;ZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doTokenize
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doDeTokenize
 * Signature: ([IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doDeTokenize
  (JNIEnv *, jobject, jintArray, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doInit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
