/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppContext */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppContext
#define _Included_org_argeo_jjml_llama_LlamaCppContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doInit
 * Signature: (JLorg/argeo/jjml/llama/LlamaCppContextParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doInit
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doGetPoolingType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doGetPoolingType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doGetContextSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doGetContextSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppContext
 * Method:    doGetBatchSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppContext_doGetBatchSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
