/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppBackend */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppBackend
#define _Included_org_argeo_jjml_llama_LlamaCppBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppBackend
 * Method:    doInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppBackend_doInit
  (JNIEnv *, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppBackend
 * Method:    doDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppBackend_doDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
