/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppEmbeddingProcessor */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
#define _Included_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
 * Method:    doProcessEmbeddings
 * Signature: ([FLorg/argeo/jjml/llama/LlamaCppContext;[[I)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor_doProcessEmbeddings
  (JNIEnv *, jobject, jfloatArray, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
