/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppModel */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppModel
#define _Included_org_argeo_jjml_llama_LlamaCppModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doInit
 * Signature: (Ljava/lang/String;Lorg/argeo/jjml/llama/LlamaCppModelParams;Ljava/util/function/DoublePredicate;)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doInit
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doTokenizeUtf8Array
 * Signature: ([BZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doTokenizeUtf8Array
  (JNIEnv *, jobject, jbyteArray, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doDeTokenizeAsUtf8Array
 * Signature: ([IZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doDeTokenizeAsUtf8Array
  (JNIEnv *, jobject, jintArray, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doTokenizeString
 * Signature: (Ljava/lang/String;ZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doTokenizeString
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doDeTokenizeAsString
 * Signature: ([IZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doDeTokenizeAsString
  (JNIEnv *, jobject, jintArray, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doFormatChatMessages
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doFormatChatMessages
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppModel
 * Method:    doGetEmbeddingSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppModel_doGetEmbeddingSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
