/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppSamplerChain */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppSamplerChain
#define _Included_org_argeo_jjml_llama_LlamaCppSamplerChain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppSamplerChain
 * Method:    doInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppSamplerChain_doInit
  (JNIEnv *, jclass);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppSamplerChain
 * Method:    doAddSampler
 * Signature: (Lorg/argeo/jjml/llama/LlamaCppNativeSampler;)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppSamplerChain_doAddSampler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppSamplerChain
 * Method:    doRemoveSampler
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppSamplerChain_doRemoveSampler
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppSamplerChain
 * Method:    doGetSampler
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppSamplerChain_doGetSampler
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppSamplerChain
 * Method:    doGetSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppSamplerChain_doGetSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
