/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppBatchProcessor */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppBatchProcessor
#define _Included_org_argeo_jjml_llama_LlamaCppBatchProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppBatchProcessor
 * Method:    doProcessBatch
 * Signature: ([Ljava/util/concurrent/CompletableFuture;Lorg/argeo/jjml/llama/LlamaCppContext;[I[[II)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppBatchProcessor_doProcessBatch
  (JNIEnv *, jobject, jobjectArray, jobject, jintArray, jobjectArray, jint);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppBatchProcessor
 * Method:    doProcessSingleBatch
 * Signature: (JLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppBatchProcessor_doProcessSingleBatch
  (JNIEnv *, jobject, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
