/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppBatchProcessor */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppBatchProcessor
#define _Included_org_argeo_jjml_llama_LlamaCppBatchProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppBatchProcessor
 * Method:    doWriteBatch
 * Signature: (JI[Ljava/nio/IntBuffer;[I[IZ)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppBatchProcessor_doWriteBatch
  (JNIEnv *, jclass, jlong, jint, jobjectArray, jintArray, jintArray, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppBatchProcessor
 * Method:    doReadBatch
 * Signature: (JI[Ljava/nio/IntBuffer;[I[ILjava/nio/channels/CompletionHandler;)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppBatchProcessor_doReadBatch
  (JNIEnv *, jclass, jlong, jint, jobjectArray, jintArray, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
