/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppEmbeddingProcessor */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
#define _Included_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppEmbeddingProcessor
 * Method:    doProcessEmbeddings
 * Signature: (J[[I[F)V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppEmbeddingProcessor_doProcessEmbeddings
  (JNIEnv *, jclass, jlong, jobjectArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
