/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppVocabulary */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppVocabulary
#define _Included_org_argeo_jjml_llama_LlamaCppVocabulary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8BytesAsArray
 * Signature: (J[BIIZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8BytesAsArray
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8AsArray
 * Signature: (JLjava/nio/ByteBuffer;IIZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8AsArray
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeUtf8
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/IntBuffer;IIZZ)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeUtf8
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeArrayAsUtf8Bytes
 * Signature: (J[IIIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeArrayAsUtf8Bytes
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsUtf8Bytes
 * Signature: (JLjava/nio/IntBuffer;IIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsUtf8Bytes
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsUtf8
 * Signature: (JLjava/nio/IntBuffer;IILjava/nio/ByteBuffer;IIZZ)I
 */
JNIEXPORT jint JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsUtf8
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doTokenizeStringAsArray
 * Signature: (JLjava/lang/String;ZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doTokenizeStringAsArray
  (JNIEnv *, jclass, jlong, jstring, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeArrayAsString
 * Signature: (J[IIIZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeArrayAsString
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jboolean, jboolean);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppVocabulary
 * Method:    doDeTokenizeAsString
 * Signature: (JLjava/nio/IntBuffer;IIZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_argeo_jjml_llama_LlamaCppVocabulary_doDeTokenizeAsString
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
