/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppNative */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppNative
#define _Included_org_argeo_jjml_llama_LlamaCppNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppNative
 * Method:    newModelParams
 * Signature: ()Lorg/argeo/jjml/llama/LlamaCppModel/Params;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_jjml_llama_LlamaCppNative_newModelParams
  (JNIEnv *, jclass);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppNative
 * Method:    newContextParams
 * Signature: ()Lorg/argeo/jjml/llama/LlamaCppContext/Params;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_jjml_llama_LlamaCppNative_newContextParams
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
