/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_jjml_llama_LlamaCppNativeSampler */

#ifndef _Included_org_argeo_jjml_llama_LlamaCppNativeSampler
#define _Included_org_argeo_jjml_llama_LlamaCppNativeSampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_jjml_llama_LlamaCppNativeSampler
 * Method:    doReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppNativeSampler_doReset
  (JNIEnv *, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppNativeSampler
 * Method:    doDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_jjml_llama_LlamaCppNativeSampler_doDestroy
  (JNIEnv *, jobject);

/*
 * Class:     org_argeo_jjml_llama_LlamaCppNativeSampler
 * Method:    doClone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_jjml_llama_LlamaCppNativeSampler_doClone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
