# Use with
# -Djava.util.logging.config.file=logging-tests.properties

# print passed tests, and more details on failed tests
.level = INFO

# print only failed tests (minimal output)
#.level = WARNING

# print inputs, outputs, durations, etc. (for analysis)
.level = FINE

handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level = FINER
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tT.%1$tL [%4$-7s] %5$s%n
