name: All Java versions

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [ "1.1" ]
  pull_request:
    branches: [ "testing", "unstable" ]

jobs:
  build:
    name: Java ${{ matrix.java }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04]
        build_type: [RelWithDebInfo]
        c_compiler: [gcc]
        cpp_compiler: [g++]
        java: ['11', '17', '21', '25' ]

    steps:
    - uses: actions/checkout@v4
      name: Clone recursively with tags
      with:
        submodules: 'true'
        fetch-depth: '0'
        fetch-tags: 'true'

    - name: Dependencies
      id: depends
      run: |
       sudo apt-get update
       sudo apt-get install -y libllama-dev

    - uses: actions/setup-java@v5
      name: Setup Java
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Configure CMake
      run: >
        cmake -B build/argeo-jjml
        -DJAVA_HOME=$JAVA_HOME
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DJJML_DO_NOT_BUILD_TP=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build build/argeo-jjml --config ${{ matrix.build_type }} -j $(nproc)

    - name: Test
      run: >
        java -ea
        -Djava.library.path=${{ github.workspace }}/build/a2/lib/$(uname -m)-linux-gnu/org.argeo.jjml
        --module-path ${{ github.workspace }}/build/a2/lib/org.argeo.jjml
        --add-modules org.argeo.jjml
        sdk/java/examples/JjmlSmokeTests.java
