name: JJML with MSVC

on:
  push:
    branches: [ "testing", "unstable" ]
  pull_request:
    branches: [ "testing", "unstable" ]

jobs:
  build:
    name: Java ${{ matrix.java }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        java: ['11', '17', '21', '25' ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4
      name: Clone recursively with tags
      with:
        submodules: 'true'
        fetch-depth: '0'
        fetch-tags: 'true'

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-java@v5
      name: Setup Java
      with:
        distribution: 'semeru'
        java-version: ${{ matrix.java }}

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DJAVA_HOME=%JAVA_HOME%
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DJJML_FORCE_BUILD_TP=ON
        -DLLAMA_CURL=OFF
        -DLLAMA_BUILD_COMMON=OFF
        -DLLAMA_BUILD_TOOLS=OFF
        -DLLAMA_BUILD_EXAMPLES=OFF
        -DLLAMA_BUILD_TESTS=OFF
        -DGGML_NATIVE=ON
        -DGGML_BACKEND_DL=OFF
        -DGGML_CPU_ALL_VARIANTS=OFF
        -DGGML_VULKAN=OFF
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j $(nproc)

    - name: Test
      run: >
        java -ea
        -Djava.library.path=${{ steps.strings.outputs.build-output-dir }}\..\a2\lib\x86_64-win32-default\org.argeo.jjml;${{ steps.strings.outputs.build-output-dir }}\..\a2\lib\x86_64-win32-default\org.argeo.tp.ggml
        --module-path ${{ steps.strings.outputs.build-output-dir }}\..\a2\org.argeo.jjml
        --add-modules org.argeo.jjml
        .\sdk\jbin\JjmlSmokeTests.java
        allenai/OLMo-2-0425-1B-Instruct-GGUF
