name: JJML Release

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [ "unstable" ]
  pull_request:
    branches: [ "testing", "unstable" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  macos-arm64:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      name: Clone recursively with tags
      with:
        submodules: 'true'
        fetch-depth: '0'
        fetch-tags: 'true'

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "${{ github.workspace }}/a2/lib/aarch64-macos-default/org.argeo.tp.ggml" >> $GITHUB_PATH

    - uses: actions/setup-java@v5
      name: Setup Java
      with:
        distribution: 'semeru'
        java-version: 21

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DJAVA_HOME=$JAVA_HOME
        -DCMAKE_SKIP_BUILD_RPATH=ON
        -DCMAKE_INSTALL_RPATH='@loader_path'
        -DJJML_FORCE_BUILD_TP=ON
        -DA2_INSTALL_MODE=a2
        -DGGML_METAL_USE_BF16=ON
        -DGGML_METAL_EMBED_LIBRARY=ON
        -DLLAMA_CURL=OFF
        -DLLAMA_BUILD_COMMON=ON
        -DLLAMA_BUILD_TOOLS=ON
        -DLLAMA_BUILD_EXAMPLES=OFF
        -DLLAMA_BUILD_TESTS=OFF
        -DGGML_BACKEND_DL=ON
        -DGGML_CPU_ALL_VARIANTS=ON
        -DGGML_VULKAN=OFF
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -j $(sysctl -n hw.logicalcpu)

    - name: Test Build
      run: >
        java -ea
        "-Djava.library.path=${{ github.workspace }}/a2/lib/aarch64-macos-default/org.argeo.jjml;${{ github.workspace }}/a2/lib/aarch64-macos-default/org.argeo.tp.ggml"
        "--module-path=${{ github.workspace }}/a2/org.argeo.jjml"
        --add-modules org.argeo.jjml
        sdk/jbin/JjmlSmokeTests.java
        allenai/OLMo-2-0425-1B-Instruct-GGUF
		