name: JJML Release

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [ "unstable" ]
  pull_request:
    branches: [ "testing", "unstable" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-x86_64:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      name: Clone recursively with tags
      with:
        submodules: 'true'
        fetch-depth: '0'
        fetch-tags: 'true'

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"
        echo "${{ github.workspace }}\a2\lib\x86_64-win32-default\org.argeo.tp.ggml" >> $GITHUB_PATH

    - uses: actions/setup-java@v5
      name: Setup Java
      with:
        distribution: 'semeru'
        java-version: 21

    - name: Dependencies
      run: |
        winget install -e --accept-source-agreements --accept-package-agreements --id WiXToolset.WiXToolset
        winget install -e --accept-source-agreements --accept-package-agreements --id GnuWin32.Make

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DJAVA_HOME=%JAVA_HOME%
        -DCMAKE_SKIP_BUILD_RPATH=ON
        -DJJML_FORCE_BUILD_TP=ON
        -DA2_INSTALL_MODE=a2
        -DLLAMA_CURL=OFF
        -DLLAMA_BUILD_COMMON=ON
        -DLLAMA_BUILD_TOOLS=ON
        -DLLAMA_BUILD_EXAMPLES=OFF
        -DLLAMA_BUILD_TESTS=OFF
        -DGGML_BACKEND_DL=ON
        -DGGML_CPU_ALL_VARIANTS=ON
        -DGGML_VULKAN=OFF
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -j $(nproc)

    - name: Test
      run: >
        java -ea
        "-Djava.library.path=${{ github.workspace }}\a2\lib\x86_64-win32-default\org.argeo.jjml;${{ github.workspace }}\a2\lib\x86_64-win32-default\org.argeo.tp.ggml"
        "--module-path=${{ github.workspace }}\a2\org.argeo.jjml"
        --add-modules org.argeo.jjml
        sdk/jbin/JjmlSmokeTests.java
        allenai/OLMo-2-0425-1B-Instruct-GGUF

    - name: Create JDK
      run: |
        gmake -f tooling.mk jdk-jjml
        cd ${{ github.workspace }}/argeo-jjml && ln -s jdk-jjml-21-openj9-x86_64-win32-default jdk-jjml-21-openj9

    - name: Create JDK .msi
      run: |
        gmake -f tooling.mk msi-jdk-jjml

  macos-aarch64:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      name: Clone recursively with tags
      with:
        submodules: 'true'
        fetch-depth: '0'
        fetch-tags: 'true'

    - name: Prepare A2 output
      run: |
        mkdir -p ${{ github.workspace }}/a2/lib/aarch64-macosx-default/jmods
        cd ${{ github.workspace }}/a2/lib && ln -s aarch64-macosx-default local

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/argeo-jjml" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-java@v5
      name: Setup Java
      with:
        distribution: 'semeru'
        java-version: 21

    - name: ccache
      uses: ggml-org/ccache-action@v1.2.16
      with:
        key: macos-arm64
        evict-old-files: 1d

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DJAVA_HOME=$JAVA_HOME
        -DJJML_FORCE_BUILD_TP=ON
        -DA2_INSTALL_MODE=a2
        -DCMAKE_SKIP_BUILD_RPATH=ON
        -DCMAKE_INSTALL_RPATH='@loader_path'
        -DGGML_METAL_USE_BF16=ON
        -DGGML_METAL_EMBED_LIBRARY=ON
        -DLLAMA_CURL=ON
        -DLLAMA_BUILD_COMMON=ON
        -DLLAMA_BUILD_TOOLS=ON
        -DLLAMA_BUILD_EXAMPLES=OFF
        -DLLAMA_BUILD_TESTS=OFF
        -DBUILD_SHARED_LIBS=ON
        -DGGML_BACKEND_DL=OFF
        -DGGML_CPU_ALL_VARIANTS=OFF
        -DGGML_VULKAN=OFF
        -DGGML_CCACHE=ON
        -DGGML_METAL=OFF
        -DGGML_BLAS=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -j $(sysctl -n hw.logicalcpu)

    - name: Test
      run: >
        DYLD_LIBRARY_PATH=${{ github.workspace }}/a2/lib/local/org.argeo.tp.ggml
        java -ea
        "-Djava.library.path=${{ github.workspace }}/a2/lib/local/org.argeo.jjml"
        "--module-path=${{ github.workspace }}/a2/org.argeo.jjml"
        --add-modules org.argeo.jjml
        sdk/jbin/JjmlSmokeTests.java

    - name: GNU Make installation
      run: |
        brew install make

    - name: Create JDK
      run: |
        gmake -f tooling.mk jdk-jjml
        cd ${{ github.workspace }}/argeo-jjml && ln -s jdk-jjml-21-openj9-aarch64-macosx-default jdk-jjml-21-openj9
        chmod +x ${{ github.workspace }}/argeo-jjml/jdk-jjml-21-openj9/bin/llama-cli
        
        # Make sure build artifacts won't be loaded during tests
        rm -rf ${{ github.workspace }}/a2

    - name: Create JDK .pkg
      run: |
        gmake -f tooling.mk pkg-jdk-jjml

    - name: Test JJML JDK
      run: >
        ${{ github.workspace }}/argeo-jjml/jdk-jjml-21-openj9/bin/java -ea
        ${{ github.workspace }}/argeo-jjml/jdk-jjml-21-openj9/man/examples/JjmlSmokeTests.java
        allenai/OLMo-2-0425-1B-Instruct-GGUF

    - name: Test llama-cli
      run: >
        DYLD_LIBRARY_PATH=${{ github.workspace }}/argeo-jjml/jdk-jjml-21-openj9/lib
        ${{ github.workspace }}/argeo-jjml/jdk-jjml-21-openj9/bin/llama-cli
        --threads $(sysctl -n hw.logicalcpu)
        --no-conversation
        --hf-repo allenai/OLMo-2-0425-1B-Instruct-GGUF
        --prompt "Describe the Java programming language in two sentences."


